import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { test } from 'node:test'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const source = (relativePath) => readFileSync(join(root, relativePath), 'utf8')

test('shared credential contract exposes store fields, workflow binding, env, and IPC channels', () => {
  const types = source('src/shared/types.ts')

  assert.match(types, /export interface Credential/)
  assert.match(types, /envKey: string/)
  assert.match(types, /createdAt: number/)
  assert.match(types, /credentialIds\?: string\[\]/)
  assert.match(types, /env\?: Record<string, string>/)
  assert.match(types, /credentialsList: 'credentials:list'/)
  assert.match(types, /credentialsSave: 'credentials:save'/)
  assert.match(types, /credentialsDelete: 'credentials:delete'/)
  assert.match(types, /credentialsGetDecrypted: 'credentials:get-decrypted'/)
})

test('main process wires CredentialStore through IPC and guards referenced deletes', () => {
  assert.equal(existsSync(join(root, 'src/main/CredentialStore.ts')), true)
  const store = source('src/main/CredentialStore.ts')
  const ipc = source('src/main/ipc.ts')
  const workflowStore = source('src/main/WorkflowStore.ts')

  assert.match(store, /credentials\.json/)
  assert.match(store, /safeStorage\.encryptString/)
  assert.match(store, /ENV_KEY_PATTERN/)
  assert.match(store, /环境变量名已存在/)
  assert.match(ipc, /new CredentialStore\(\)/)
  assert.match(ipc, /ipcMain\.handle\(IPC\.credentialsList/)
  assert.match(ipc, /ipcMain\.handle\(IPC\.credentialsSave/)
  assert.match(ipc, /ipcMain\.handle\(IPC\.credentialsGetDecrypted/)
  assert.match(ipc, /ipcMain\.handle\(IPC\.credentialsDelete/)
  assert.match(ipc, /template\.credentialIds/)
  assert.match(ipc, /该凭据正在被/)
  assert.match(workflowStore, /credentialIds: input\.credentialIds \?\? \[\]/)
  assert.match(workflowStore, /credentialIds: t\.credentialIds \?\? \[\]/)
})

test('workflow runtime injects only selected credentials into process env', () => {
  const manager = source('src/main/WorkflowManager.ts')
  const runManager = source('src/main/RunManager.ts')
  const adapterTypes = source('src/main/adapters/types.ts')
  const claude = source('src/main/adapters/claudeAdapter.ts')
  const codex = source('src/main/adapters/codexAdapter.ts')
  const apiAdapter = source('src/main/adapters/apiAdapter.ts')
  const bashTool = source('src/main/adapters/api-tools/bash.ts')

  assert.match(manager, /private readonly credentialStore\?: CredentialStore/)
  assert.match(manager, /credentialIds: template\.credentialIds \?\? \[\]/)
  assert.match(manager, /private credentialEnvForRun\(run: WorkflowRun\)/)
  assert.match(manager, /this\.credentialStore\.getDecrypted\(id\)/)
  assert.match(manager, /env\[credential\.envKey\] = credential\.value/)
  assert.match(manager, /console\.warn\(`\[CredentialStore\] Skipping credential/)
  assert.match(manager, /env: this\.credentialEnvForRun\(run\)/)
  assert.match(runManager, /env: config\.env/)
  assert.match(adapterTypes, /env\?: Record<string, string>/)
  assert.match(claude, /env: input\.env \? \{ \.\.\.process\.env, \.\.\.input\.env \}/)
  assert.match(codex, /env: input\.env \? \{ \.\.\.process\.env, \.\.\.input\.env \}/)
  assert.match(apiAdapter, /buildToolSet[\s\S]*input\.env/)
  assert.match(bashTool, /env: env \? \{ \.\.\.process\.env, \.\.\.env \} : process\.env/)
})

test('renderer exposes Credentials settings and reusable workflow credential drawer', () => {
  assert.equal(existsSync(join(root, 'src/renderer/src/CredentialDrawer.tsx')), true)
  assert.equal(existsSync(join(root, 'src/renderer/src/CredentialSettings.tsx')), true)
  assert.equal(existsSync(join(root, 'src/renderer/src/useCredentials.ts')), true)

  const preload = source('src/preload/index.ts')
  const settings = source('src/renderer/src/SettingsPanel.tsx')
  const drawer = source('src/renderer/src/CredentialDrawer.tsx')
  const credentialSettings = source('src/renderer/src/CredentialSettings.tsx')
  const templates = source('src/renderer/src/TemplatesView.tsx')
  const canvas = source('src/renderer/src/canvas/WorkflowCanvas.tsx')
  const styles = source('src/renderer/src/styles.css')

  assert.match(preload, /credentialsList: \(\)/)
  assert.match(preload, /credentialsSave: \(input:/)
  assert.match(preload, /credentialsDelete: \(id: string\)/)
  assert.match(preload, /credentialsGetDecrypted: \(id: string\)/)
  assert.match(settings, /Credentials/)
  assert.match(settings, /const credentialState = useCredentials\(\)/)
  assert.match(settings, /<CredentialSettings \{\.\.\.credentialState\} \/>/)
  assert.match(drawer, /GOOGLE_SERVICE_ACCOUNT_JSON/)
  assert.match(drawer, /SEMRUSH_API_KEY/)
  assert.match(drawer, /PROJECT_DOMAIN/)
  assert.match(drawer, /duplicateEnvKey/)
  assert.match(drawer, /留空则保留已保存的值/)
  assert.match(drawer, /createPortal/)
  assert.match(drawer, /credential-drawer-overlay/)
  assert.match(credentialSettings, /setMessage\(err instanceof Error \? err\.message/)
  assert.match(templates, /credentialIds: editCredentialIds/)
  assert.match(templates, /onTemplateCredentialIdsChange/)
  assert.match(canvas, /workflow-template-credentials/)
  assert.match(canvas, /CredentialDrawer/)
  assert.doesNotMatch(canvas, /placement="template-adjacent"/)
  assert.match(canvas, /onCredentialIdsChange/)
  assert.match(styles, /\.credential-row/)
  assert.match(styles, /\.workflow-template-credential-item/)
  assert.doesNotMatch(styles, /credential-drawer-overlay-template-adjacent/)
  assert.match(styles, /credential-drawer-slide-in/)
})
