import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const css = readFileSync(join(root, 'src/renderer/src/styles.css'), 'utf8')
const workspace = readFileSync(join(root, 'src/renderer/src/WorkflowWorkspace.tsx'), 'utf8')
const runsList = readFileSync(join(root, 'src/renderer/src/WorkflowRunsList.tsx'), 'utf8')
const selectComponent = readFileSync(join(root, 'src/renderer/src/Select.tsx'), 'utf8')
const scheduleList = readFileSync(join(root, 'src/renderer/src/ScheduleList.tsx'), 'utf8')
const detail = readFileSync(join(root, 'src/renderer/src/WorkflowRunDetail.tsx'), 'utf8')
const handoff = readFileSync(join(root, 'src/renderer/src/HandoffPanel.tsx'), 'utf8')
const drawer = readFileSync(join(root, 'src/renderer/src/NewWorkflowRunDrawer.tsx'), 'utf8')
const templatesView = readFileSync(join(root, 'src/renderer/src/TemplatesView.tsx'), 'utf8')
const workflowCanvas = readFileSync(join(root, 'src/renderer/src/canvas/WorkflowCanvas.tsx'), 'utf8')
const canvasSerializer = readFileSync(join(root, 'src/renderer/src/canvas/canvasSerializer.ts'), 'utf8')
const canvasState = readFileSync(join(root, 'src/renderer/src/canvas/useCanvasState.ts'), 'utf8')
const agentNode = readFileSync(join(root, 'src/renderer/src/canvas/AgentNode.tsx'), 'utf8')
const app = readFileSync(join(root, 'src/renderer/src/App.tsx'), 'utf8')
const mainIndex = readFileSync(join(root, 'src/main/index.ts'), 'utf8')
const workflowManager = readFileSync(join(root, 'src/main/WorkflowManager.ts'), 'utf8')
const fixture = readFileSync(join(root, 'src/renderer/src/uiReviewFixture.ts'), 'utf8')
const mockNav = readFileSync(join(root, 'src/renderer/src/UiReviewMockNav.tsx'), 'utf8')
const sharedTypes = readFileSync(join(root, 'src/shared/types.ts'), 'utf8')
const modeRail = readFileSync(join(root, 'src/renderer/src/ModeRail.tsx'), 'utf8')
const settingsPanel = readFileSync(join(root, 'src/renderer/src/SettingsPanel.tsx'), 'utf8')
const scheduleWorkspace = readFileSync(join(root, 'src/renderer/src/ScheduleWorkspace.tsx'), 'utf8')
const agentManager = readFileSync(join(root, 'src/renderer/src/AgentManager.tsx'), 'utf8')

function rootBlock(selector) {
  const pattern = new RegExp(`${selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*\\{([^}]*)\\}`)
  return css.match(pattern)?.[1] ?? ''
}

function lastRootBlock(selector) {
  const pattern = new RegExp(`(?:^|\\n)${selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*\\{([^}]*)\\}`, 'g')
  const matches = [...css.matchAll(pattern)]
  return matches.at(-1)?.[1] ?? ''
}

test('workflow workspace uses card page with run detail route', () => {
  assert.match(css, /\.workflow-workspace\s*\{/)
  assert.match(workspace, /WorkflowRunsList/)
  assert.match(workspace, /WorkflowRunDetail/)
  assert.match(workspace, /workflowView/)
  assert.match(workspace, /'runs' \| 'run-detail'/)
  assert.match(runsList, /workflow-dashboard-page/)
  assert.match(workspace, /workflow-detail-page/)
  assert.match(workspace, /onBack/)
  assert.doesNotMatch(workspace, /className="detail-header"/)
  assert.match(detail, /onBack\?: \(\) => void/)
  assert.match(detail, /ChevronLeft/)
  assert.match(detail, /className="btn btn-ghost btn-sm workflow-detail-back icon-only"/)
  assert.match(detail, /onClick=\{onBack\}/)
  assert.doesNotMatch(detail, />\s*返回\s*</)
  assert.match(css, /\.workflow-run-detail-heading\s*\{[\s\S]*display:\s*flex !important;[\s\S]*align-items:\s*center !important;/)
  assert.doesNotMatch(workspace, /workflow-tabs/)
  assert.doesNotMatch(workspace, /ScheduleList/)
  assert.doesNotMatch(workspace, /ScheduleDetail/)
})

test('schedule workspace is a standalone card page with detail route', () => {
  const cardPageBlock = css.match(/\.workflow-dashboard-page,\s*\n\.schedule-dashboard-page,\s*\n\.workflow-detail-page,\s*\n\.schedule-detail-page\s*\{([\s\S]*?)\n\}/)?.[1] ?? ''

  assert.match(scheduleWorkspace, /ScheduleList/)
  assert.match(scheduleWorkspace, /ScheduleDetail/)
  assert.match(scheduleWorkspace, /ScheduleDrawer/)
  assert.match(scheduleWorkspace, /scheduleState\?: UseSchedulesResult/)
  assert.match(scheduleWorkspace, /const schedules = scheduleState \?\? liveSchedules/)
  assert.match(scheduleWorkspace, /scheduleView/)
  assert.match(scheduleWorkspace, /'schedules' \| 'schedule-detail'/)
  assert.match(scheduleList, /schedule-dashboard-page/)
  assert.match(scheduleWorkspace, /schedule-detail-page/)
  assert.match(scheduleWorkspace, /onBack/)
  assert.match(css, /\.workflow-dashboard-page,\s*\n\.schedule-dashboard-page/)
  assert.match(css, /\.workflow-detail-page,\s*\n\.schedule-detail-page/)
  assert.match(cardPageBlock, /padding:\s*10px 24px !important;/)
})

test('schedule cards stay compact and left aligned', () => {
  const scheduleGridBlock = lastRootBlock('.schedule-cards.cards-grid')
  const scheduleCardBlock = lastRootBlock('.schedule-card')
  const scheduleNameBlock = lastRootBlock('.schedule-card-name')
  const scheduleTimingBlock = lastRootBlock('.schedule-countdown-wrap')
  const scheduleFooterBlock = lastRootBlock('.schedule-card-footer')

  assert.match(scheduleGridBlock, /grid-template-columns:\s*repeat\(auto-fill,\s*minmax\(min\(360px,\s*100%\),\s*420px\)\) !important;/)
  assert.match(scheduleGridBlock, /justify-content:\s*start !important;/)
  assert.match(scheduleGridBlock, /align-items:\s*start !important;/)
  assert.match(css, /@media \(max-width: 900px\) \{[\s\S]*\.cards-grid,\s*\n\s*\.workflow-run-cards\.cards-grid\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\) !important;[\s\S]*\.schedule-cards\.cards-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(auto-fill,\s*minmax\(min\(360px,\s*100%\),\s*420px\)\) !important;/)
  assert.doesNotMatch(css, /@media \(max-width: 900px\) \{[\s\S]*\.workflow-run-cards\.cards-grid,\s*\n\s*\.schedule-cards\.cards-grid/)
  assert.match(scheduleCardBlock, /min-height:\s*0 !important;/)
  assert.match(scheduleCardBlock, /align-items:\s*stretch !important;/)
  assert.match(scheduleCardBlock, /justify-content:\s*flex-start !important;/)
  assert.match(scheduleCardBlock, /text-align:\s*left !important;/)
  assert.match(scheduleNameBlock, /text-align:\s*left !important;/)
  assert.match(scheduleTimingBlock, /display:\s*flex !important;/)
  assert.match(scheduleTimingBlock, /flex-wrap:\s*wrap !important;/)
  assert.match(scheduleFooterBlock, /margin-top:\s*2px !important;/)
})

test('agent manager list items keep a stable two-line rhythm', () => {
  const agentItemBlock = lastRootBlock('.agent-item')
  const agentTitleRowBlock = lastRootBlock('.agent-item-title-row')
  const agentNameBlock = lastRootBlock('.agent-item-name')
  const agentMetaBlock = lastRootBlock('.agent-item-meta')

  assert.match(agentItemBlock, /display:\s*flex !important;/)
  assert.match(agentItemBlock, /flex-direction:\s*column !important;/)
  assert.match(agentItemBlock, /flex:\s*0 0 auto !important;/)
  assert.match(agentItemBlock, /min-height:\s*78px !important;/)
  assert.match(agentItemBlock, /gap:\s*7px !important;/)
  assert.match(agentItemBlock, /margin:\s*0 !important;/)
  assert.match(agentItemBlock, /overflow:\s*hidden !important;/)
  assert.match(agentTitleRowBlock, /min-height:\s*24px !important;/)
  assert.match(agentTitleRowBlock, /line-height:\s*1\.25 !important;/)
  assert.match(agentNameBlock, /line-height:\s*1\.3 !important;/)
  assert.match(agentMetaBlock, /display:\s*block !important;/)
  assert.match(agentMetaBlock, /line-height:\s*1\.45 !important;/)
})

test('empty dashboards keep their create cards visible', () => {
  assert.match(agentManager, /<div className="agent-cards-grid">/)
  assert.match(agentManager, /agents\.length > 0 && filteredAgents\.length === 0/)
  assert.match(agentManager, /className="agent-card agent-card-new"/)
  assert.doesNotMatch(agentManager, /filteredAgents\.length === 0 \?/)

  assert.match(scheduleList, /function CreateScheduleCard/)
  assert.match(scheduleList, /className="schedule-card dashboard-create-card schedule-create-card"/)
  assert.match(scheduleList, /!\s*loading && \(/)
  assert.doesNotMatch(scheduleList, /暂无定时任务/)

  assert.match(runsList, /function CreateWorkflowRunCard/)
  assert.match(runsList, /dashboardRuns\.length > 0 && filteredRuns\.length === 0/)
  assert.match(runsList, /className="workflow-run-card dashboard-create-card workflow-run-create-card"/)
  assert.match(css, /\.dashboard-create-card\s*\{/)
  assert.match(css, /\.schedule-create-card\s*\{/)
  assert.match(css, /\[data-theme="dark"\] \.dashboard-create-card\s*\{/)
})

test('runs list uses design cards without realtime tail or confirm button', () => {
  const cardAnimationBlock = css.match(/\.workflow-run-card,\s*\n\.schedule-card\s*\{([\s\S]*?)\n\}/)?.[1] ?? ''

  assert.match(runsList, /onSelectRun/)
  assert.match(runsList, /page-title/)
  assert.match(runsList, /workflow-run-card-top/)
  assert.match(runsList, /workflow-run-card-meta/)
  assert.match(runsList, /workflow-run-card-time/)
  assert.match(runsList, /workflow-run-card-footer/)
  assert.match(runsList, /workflowRunProgressSegments/)
  assert.match(runsList, /workflow-run-card-progress/)
  assert.match(runsList, /workflowRunCardTitle/)
  assert.doesNotMatch(runsList, /点击 workflow run 卡片进入详情。/)
  assert.match(runsList, /workflowRunModelTags\(run, agentById\)/)
  assert.match(workspace, /<WorkflowRunsList[\s\S]*agents=\{agents\}/)
  assert.match(runsList, /agents: AgentDefinition\[\]/)
  assert.match(runsList, /agentById\.get\(step\.agentId\)/)
  assert.match(runsList, /step\.model\?\.trim\(\)/)
  assert.doesNotMatch(runsList, /const fullLabel = workflowRunStepLabel\(step, index\)/)
  assert.match(runsList, /workflow-run-card-model-tags/)
  assert.match(runsList, /workflow-run-card-model-tag-/)
  assert.ok(runsList.includes("replace(/^\\s*\\[scheduled\\]\\s*/i, '')"))
  assert.match(runsList, /workflow-run-scheduled-badge/)
  assert.match(css, /\.workflow-run-card-top\s*\{/)
  assert.match(css, /\.workflow-run-card-footer\s*\{[\s\S]*align-items:\s*center;[\s\S]*justify-content:\s*space-between;/)
  assert.match(css, /\.workflow-run-card-footer \.workflow-run-card-status\s*\{[\s\S]*margin-left:\s*auto;[\s\S]*align-self:\s*center;/)
  assert.match(css, /\.workflow-run-card-progress\s*\{[\s\S]*position:\s*relative !important;[\s\S]*overflow:\s*hidden !important;/)
  assert.match(css, /\.workflow-run-card-running \.workflow-run-card-progress::after[\s\S]*\{[\s\S]*animation:\s*running-progress-sweep/)
  assert.match(css, /@keyframes running-progress-sweep/)
  assert.match(css, /\.workflow-run-card-status-running[\s\S]*\{[\s\S]*var\(--semantic-running\)/)
  assert.match(css, /\.workflow-run-card-status-running::before[\s\S]*\{[\s\S]*animation:\s*running-dot-pulse/)
  assert.match(css, /@keyframes running-dot-pulse/)
  assert.match(css, /\.workflow-run-card-segment-running\s*\{[\s\S]*animation:\s*running-segment-flow/)
  assert.match(css, /@keyframes running-segment-flow/)
  assert.match(css, /\.workflow-run-card-model-tag-running\s*\{[\s\S]*color:\s*var\(--semantic-running\)/)
  assert.match(css, /\.workflow-run-card-model-tag-running\s*\{[\s\S]*animation:\s*running-chip-breathe/)
  assert.match(css, /\.workflow-run-card-step-pill-running\s*\{[\s\S]*color:\s*var\(--semantic-running\)/)
  assert.match(css, /\.workflow-run-card-step-pill-running\s*\{[\s\S]*animation:\s*running-chip-breathe/)
  assert.match(css, /@keyframes running-chip-breathe/)
  assert.match(css, /\.workflow-step-chip-running\s*\{[\s\S]*animation:\s*running-chip-breathe/)
  assert.match(css, /\.workflow-run-step-dot-running,[\s\S]*\.workflow-step-status-dot-running\s*\{[\s\S]*animation:\s*running-dot-pulse/)
  assert.match(css, /\.parallel-tab-dot-running\s*\{[\s\S]*animation:\s*running-dot-pulse/)
  assert.match(css, /prefers-reduced-motion:\s*reduce[\s\S]*\.workflow-run-card-running \.workflow-run-card-progress::after[\s\S]*animation:\s*none !important/)
  assert.match(css, /\.workflow-run-card-segment-waiting\s*\{[\s\S]*var\(--semantic-warning\)/)
  assert.match(css, /\.workflow-run-card-model-tags\s*\{[\s\S]*display:\s*flex !important;[\s\S]*flex-wrap:\s*wrap !important;/)
  assert.match(css, /\.workflow-run-card-model-tag\s*\{[\s\S]*border-radius:\s*6px !important;[\s\S]*font-size:\s*10px !important;/)
  assert.match(css, /\.workflow-run-card-step-pills\s*\{[\s\S]*max-height:\s*30px !important;[\s\S]*overflow-x:\s*auto !important;[\s\S]*overflow-y:\s*hidden !important;/)
  assert.match(runsList, /workflow-run-card-step-pill-label/)
  assert.doesNotMatch(runsList, /CircleDot/)
  assert.doesNotMatch(runsList, /workflow-run-status-icon/)
  assert.doesNotMatch(css, /workflow-run-status-icon/)
  assert.doesNotMatch(css, /\.workflow-run-card-step-pill svg/)
  assert.match(css, /\.workflow-run-scheduled-badge\s*\{[\s\S]*var\(--semantic-warning\)/)
  assert.match(cardAnimationBlock, /animation:\s*card-enter 420ms/)
  assert.doesNotMatch(cardAnimationBlock, /opacity:\s*0 !important/)
  assert.doesNotMatch(cardAnimationBlock, /transform:\s*translateY\(16px\) !important/)
  assert.match(css, /\.workflow-run-card-status-completed\s*\{[\s\S]*var\(--semantic-success\)/)
  assert.match(css, /\.workflow-run-status-awaiting-confirm,\s*\n\.workflow-run-status-awaiting-input,\s*\n\.workflow-run-card-status-awaiting-input,\s*\n\.workflow-run-card-status-awaiting-confirm\s*\{[\s\S]*color:\s*var\(--semantic-warning\);[\s\S]*background:\s*rgba\(201,\s*149,\s*44,\s*0\.08\);/)
  assert.match(css, /\.cards-grid,\s*\n\.workflow-run-cards\.cards-grid,\s*\n\.schedule-cards\.cards-grid\s*\{[\s\S]*padding:\s*6px 2px 24px !important;[\s\S]*scroll-padding-top:\s*6px !important;/)
  assert.match(css, /\.workflow-run-card:hover,\s*\n\.schedule-card:hover\s*\{[\s\S]*transform:\s*translateY\(-3px\) !important;/)
  assert.match(css, /\[data-theme="dark"\] \.workflow-run-card\s*\{[\s\S]*background:\s*rgba\(15, 25, 45, 0\.64\) !important;/)
  assert.match(css, /\[data-theme="dark"\] \.workflow-run-card:hover\s*\{[\s\S]*background:\s*rgba\(0, 212, 170, 0\.06\) !important;/)
  assert.match(css, /\[data-theme="dark"\] \.workflow-run-card\.workflow-run-card-active\s*\{[\s\S]*rgba\(15, 25, 45, 0\.88\) !important;[\s\S]*color:\s*var\(--neutral-text-primary\) !important;/)
  assert.match(css, /\[data-theme="dark"\] \.workflow-run-card\.workflow-run-card-active \.workflow-run-scheduled-badge\s*\{[\s\S]*color:\s*var\(--semantic-warning\) !important;/)
  assert.doesNotMatch(runsList, /workflowRunTailLines/)
  assert.doesNotMatch(runsList, /workflow-run-card-tail/)
  assert.doesNotMatch(runsList, /Sound On|Sound Off/)
  assert.doesNotMatch(runsList, /section-title">Workflow Runs/)
  assert.doesNotMatch(runsList, /确认详情|Confirm/)
})

test('run cards use option B internal scrolling for long step pill lists', () => {
  const workflowRunGridBlock = lastRootBlock('.workflow-run-cards.cards-grid')
  const workflowRunCardBlock = lastRootBlock('.workflow-run-card')
  const stepPillsBlock = lastRootBlock('.workflow-run-card-step-pills')
  const stepPillBlock = lastRootBlock('.workflow-run-card-step-pill')

  assert.match(runsList, /run\.steps\.map/)
  assert.match(runsList, /const modelLabel = step\.model\?\.trim\(\) \|\| agent\?\.model\?\.trim\(\)/)
  assert.match(runsList, /\.slice\(0, 3\)/)
  assert.doesNotMatch(runsList, /MAX_WORKFLOW_RUN_CARD_STEP_PILLS/)
  assert.doesNotMatch(runsList, /visibleStepPillCount/)
  assert.doesNotMatch(runsList, /hiddenSteps/)
  assert.doesNotMatch(runsList, /workflow-run-card-step-pill-more/)

  assert.match(workflowRunGridBlock, /align-items:\s*start !important;/)
  assert.match(workflowRunGridBlock, /grid-auto-rows:\s*240px !important;/)
  assert.match(workflowRunGridBlock, /row-gap:\s*24px !important;/)
  assert.match(workflowRunCardBlock, /align-self:\s*stretch !important;/)
  assert.match(workflowRunCardBlock, /min-height:\s*240px !important;/)
  assert.match(workflowRunCardBlock, /height:\s*240px !important;/)
  assert.match(css, /\.workflow-run-card-top\s*\{[\s\S]*flex-shrink:\s*0 !important;[\s\S]*overflow:\s*visible !important;/)
  assert.match(css, /\.workflow-run-card-meta\s*\{[\s\S]*flex-shrink:\s*0 !important;/)
  assert.match(css, /\.workflow-run-card-steps\s*\{[\s\S]*min-width:\s*0 !important;[\s\S]*overflow:\s*hidden !important;/)
  assert.match(css, /\.workflow-run-card-steps\s*\{[\s\S]*flex-shrink:\s*0 !important;/)
  assert.match(stepPillsBlock, /display:\s*flex !important;/)
  assert.match(stepPillsBlock, /flex-wrap:\s*nowrap !important;/)
  assert.match(stepPillsBlock, /gap:\s*6px 8px !important;/)
  assert.match(stepPillsBlock, /max-height:\s*30px !important;/)
  assert.match(stepPillsBlock, /overflow-x:\s*auto !important;/)
  assert.match(stepPillsBlock, /overflow-y:\s*hidden !important;/)
  assert.match(stepPillsBlock, /scrollbar-width:\s*thin !important;/)
  assert.doesNotMatch(stepPillsBlock, /grid-template-columns:/)
  assert.match(stepPillBlock, /flex:\s*0 0 auto !important;/)
  assert.match(stepPillBlock, /width:\s*fit-content !important;/)
  assert.match(stepPillBlock, /max-width:\s*100% !important;/)
  assert.match(stepPillBlock, /padding:\s*2px 8px !important;/)
  assert.match(stepPillBlock, /border-radius:\s*6px !important;/)
  assert.match(stepPillBlock, /font-size:\s*10px !important;/)
  assert.match(stepPillBlock, /font-weight:\s*700 !important;/)
  assert.match(stepPillBlock, /line-height:\s*1\.35 !important;/)
  assert.match(css, /\.workflow-run-card-footer\s*\{[\s\S]*overflow:\s*visible !important;/)
  assert.match(css, /\.workflow-run-card-footer\s*\{[\s\S]*flex-shrink:\s*0 !important;/)
})

test('workflow run cards persist and display agent model tags', () => {
  assert.match(sharedTypes, /export interface WorkflowRunStep\s*\{[\s\S]*vendor\?: AgentVendor[\s\S]*model\?: string[\s\S]*apiProviderId\?: string/)
  assert.match(workflowManager, /vendor: agent\?\.vendor/)
  assert.match(workflowManager, /model: agent\?\.model\?\.trim\(\) \|\| undefined/)
  assert.match(workflowManager, /apiProviderId: agent\?\.apiProviderId/)
  assert.match(fixture, /vendor: agent\?\.vendor/)
  assert.match(fixture, /model: agent\?\.model\?\.trim\(\) \|\| undefined/)
  assert.match(runsList, /const modelLabel = step\.model\?\.trim\(\) \|\| agent\?\.model\?\.trim\(\)/)
  assert.match(runsList, /agent\?\.model\?\.trim\(\)/)
  assert.match(runsList, /return run\.steps[\s\S]*\.map\(\(step\) => \{/)
  assert.doesNotMatch(runsList, /workflowRunModelTagLabel\(fullLabel\)/)
})

test('step navigation lives inside run detail with chip bar', () => {
  assert.match(detail, /workflow-step-nav/)
  assert.match(detail, /workflow-step-chip/)
  assert.match(detail, /step\.displayName/)
  assert.match(sharedTypes, /displayName\?: string/)
  assert.match(detail, /for \(let index = 0; index < run\.steps\.length; index\+\+\)/)
  assert.doesNotMatch(detail, /items: \[\{ step, index: 0 \}\]/)
})

test('run detail owns transcript, artifact cards, composer, and preview pane', () => {
  assert.match(detail, /TranscriptViewer/)
  assert.match(detail, /ArtifactCard/)
  assert.match(detail, /FilePreviewPane/)
  assert.match(detail, /const \[rightTab, setRightTab\] = useState<'task' \| 'files' \| 'output'>\('task'\)/)
  assert.match(detail, /activeTab: 'task' \| 'files' \| 'output'/)
  assert.doesNotMatch(detail, /ClipboardList/)
  assert.match(detail, />\s*任务\s*</)
  assert.match(detail, /workflow-side-task/)
  assert.match(detail, /<span className="workflow-prompt-label">任务描述<\/span>/)
  assert.doesNotMatch(detail, /workflow-side-task-edit/)
  assert.doesNotMatch(detail, /点击编辑/)
  assert.doesNotMatch(detail, /<div className="workflow-prompt-section">/)
  assert.match(detail, /workflow-cli-composer/)
  assert.match(detail, /codex-layout/)
  assert.match(detail, /codex-left/)
  assert.match(detail, /codex-right/)
  assert.match(css, /\.workflow-side-task-display \.workflow-prompt-text\s*\{[\s\S]*white-space:\s*pre-wrap;[\s\S]*overflow-wrap:\s*anywhere;/)
  assert.match(css, /\.composer-chip-remove\s*\{[\s\S]*height:\s*16px;[\s\S]*min-height:\s*16px;/)
  assert.match(css, /\.composer-chip-remove:hover\s*\{[\s\S]*background:\s*transparent;[\s\S]*color:\s*var\(--red\);/)
  assert.doesNotMatch(css, /\.composer-chip-remove:hover\s*\{[^}]*background:\s*rgba/)
  assert.match(detail, /重新运行步骤/)
  assert.match(detail, /Stop/)
})

test('new workflow run starts from a drawer with git safety confirmation', () => {
  const worktreeCheckboxBlock = lastRootBlock('.workflow-worktree-checkbox')
  const worktreeOnCheckboxBlock = lastRootBlock('.workflow-worktree-toggle-on .workflow-worktree-checkbox')
  const worktreeCheckboxInputBlock = lastRootBlock('.workflow-worktree-checkbox input')
  const worktreeCheckboxStateBlock =
    css.match(/\.workflow-worktree-checkbox input:checked,\s*\.workflow-worktree-checkbox input:active,\s*\.workflow-worktree-checkbox input:focus,\s*\.workflow-worktree-checkbox input:focus-visible\s*\{([^}]*)\}/)?.[1] ?? ''

  assert.match(drawer, /workflow-run-create-drawer/)
  assert.match(drawer, /workflow-schedule-drawer/)
  assert.doesNotMatch(drawer, /createPortal/)
  assert.doesNotMatch(drawer, /document\.body/)
  assert.doesNotMatch(drawer, /workflow-new-run-overlay/)
  assert.match(drawer, /新建工作流/)
  assert.match(drawer, /工作流模板/)
  assert.match(drawer, /运行名称/)
  assert.match(drawer, /项目路径/)
  assert.match(drawer, /在隔离副本中运行/)
  assert.match(drawer, /workflow-worktree-toggle/)
  assert.match(drawer, /workflow-worktree-checkbox/)
  assert.match(drawer, /workflow-worktree-crumb-branch/)
  assert.match(drawer, /useWorktree/)
  assert.match(worktreeCheckboxBlock, /border:\s*none !important;/)
  assert.match(worktreeCheckboxBlock, /background:\s*transparent !important;/)
  assert.doesNotMatch(worktreeOnCheckboxBlock, /border(?:-color)?:/)
  assert.match(worktreeCheckboxInputBlock, /border:\s*none !important;/)
  assert.match(worktreeCheckboxInputBlock, /outline:\s*none !important;/)
  assert.match(worktreeCheckboxInputBlock, /box-shadow:\s*none !important;/)
  assert.match(worktreeCheckboxStateBlock, /border:\s*none !important;/)
  assert.match(worktreeCheckboxStateBlock, /outline:\s*none !important;/)
  assert.match(worktreeCheckboxStateBlock, /box-shadow:\s*none !important;/)
  assert.match(drawer, /Browse project directory/)
  assert.match(drawer, /onInspectGitSafety/)
  assert.match(drawer, /allowUnsafeSameGitRoot/)
  assert.match(drawer, /runningRunCount/)
  assert.match(drawer, /allowHighConcurrency/)
  assert.match(drawer, /5/)
  assert.match(drawer, /仍然启动/)
  assert.match(drawer, /Git 安全检查/)
  assert.match(drawer, /workflow-git-safety-card/)
  assert.match(drawer, /初始指令/)
  assert.match(drawer, /步骤预览/)
  assert.match(drawer, /workflow-template-preview-pills/)
  assert.match(drawer, /initialRunName/)
  assert.match(drawer, /initialProjectPath/)
  assert.match(drawer, /initialPrompt/)
  assert.match(drawer, />\s*取消\s*</)
  assert.match(drawer, />\s*启动运行\s*</)
  assert.match(css, /grid-template-rows:\s*auto minmax\(0,\s*1fr\) auto;/)
  assert.match(css, /\.workflow-new-run-drawer\s*\{[\s\S]*width:\s*min\(500px, calc\(100vw - 40px\)\) !important;[\s\S]*backdrop-filter:\s*var\(--glass-blur-heavy\) !important;/)
  assert.match(css, /\.workflow-schedule-drawer\s*\{[\s\S]*flex:\s*0 0 min\(360px, 100vw\) !important;[\s\S]*width:\s*min\(360px, 100vw\) !important;[\s\S]*max-width:\s*min\(360px, 100vw\) !important;/)
})

test('main navigation includes standalone schedules mode', () => {
  assert.match(modeRail, /type WorkspaceMode = 'workflow' \| 'schedules' \| 'templates' \| 'agents' \| 'single' \| 'settings'/)
  assert.match(app, /TemplatesView/)
  assert.match(app, /case 'templates':\s*return '模板编辑'/)
  assert.match(app, /case 'schedules':\s*return '定时任务'/)
  assert.match(app, /case 'settings':\s*return '系统设置'/)
  assert.match(app, /ScheduleWorkspace/)
  assert.match(app, /scheduleState=\{uiReview\.enabled \? uiReview\.schedules : undefined\}/)
  assert.match(templatesView, /templates-sidebar-head/)
  assert.match(templatesView, /<h2>模板<\/h2>/)
  assert.match(modeRail, /key: 'workflow'[\s\S]*key: 'schedules'[\s\S]*key: 'templates'[\s\S]*key: 'agents'[\s\S]*key: 'single'/)
  assert.match(modeRail, /mode-rail-spacer[\s\S]*onModeChange\('settings'\)/)
  assert.match(modeRail, /railIcon\(item\.key\)/)
  assert.match(modeRail, /mode-rail-btn/)
  assert.match(modeRail, /title=\{item\.label\}/)
  assert.doesNotMatch(modeRail, /Single Run/)
  assert.doesNotMatch(app, /New Workflow Run['"]\s*\)/)
})

test('green redesign shell, theme settings, and page chrome are wired', () => {
  assert.match(sharedTypes, /export type AppearanceTheme = 'light' \| 'dark'/)
  assert.match(sharedTypes, /appearanceTheme: AppearanceTheme/)
  assert.match(sharedTypes, /appearanceTheme: 'light'/)
  assert.match(app, /document\.documentElement\.dataset\.theme = appearanceTheme/)
  assert.match(app, /className="chinese-pattern-bg"/)
  assert.match(app, /className="tech-grid-bg"/)
  assert.match(app, /className="theme-toggle"/)
  assert.doesNotMatch(app, /<span>\{appearanceTheme === 'dark' \? '亮' : '暗'\}<\/span>/)
  assert.match(app, /Moon[\s\S]*Sun/)
  assert.match(modeRail, /LayoutGrid[\s\S]*CalendarClock[\s\S]*Layers[\s\S]*Bot[\s\S]*MessageCircle[\s\S]*Settings/)
  assert.match(css, /Green UI redesign overrides/)
  assert.match(css, /--brand-primary:\s*#3d8e86/)
  assert.match(css, /--semantic-running:\s*#3b82f6/)
  assert.match(css, /\[data-theme="dark"\]\s*\{[\s\S]*--brand-primary:\s*#00d4aa/)
  assert.match(css, /\[data-theme="dark"\]\s*\{[\s\S]*--semantic-running:\s*#60a5fa/)
  assert.match(css, /\.app-header\s*\{[\s\S]*padding:\s*0 24px 0 86px;/)
  assert.match(css, /\.app-header h1\s*\{[\s\S]*white-space:\s*nowrap;/)
  assert.match(css, /\.mode-rail-btn\s*\{[\s\S]*width:\s*44px;[\s\S]*height:\s*44px;/)
  assert.match(runsList, /new-run-btn/)
  assert.doesNotMatch(runsList, /workflow-run-filters|FILTERS|FilterKey/)
  assert.match(detail, /WorkflowSidePanel/)
  assert.match(detail, /workflow-right-panel/)
  assert.doesNotMatch(detail, /route-suggestion-inline/)
  assert.doesNotMatch(detail, /Agent 建议/)
  assert.match(settingsPanel, /SETTINGS_NAV/)
  assert.match(settingsPanel, /section-preference/)
  assert.match(settingsPanel, /appearanceTheme: settings\.appearanceTheme === 'dark' \? 'light' : 'dark'/)
  assert.match(css, /Settings sidebar and workflow side-panel QA overrides/)
  assert.match(css, /\.settings-sidebar\s*\{[\s\S]*width:\s*220px !important;/)
  assert.match(css, /\.settings-content\s*\{[\s\S]*max-width:\s*640px !important;/)
  assert.match(css, /\.settings-nav-item\s*\{[\s\S]*display:\s*flex !important;[\s\S]*align-items:\s*center !important;[\s\S]*gap:\s*10px !important;[\s\S]*border:\s*0 !important;[\s\S]*justify-content:\s*flex-start !important;[\s\S]*box-shadow:\s*none !important;/)
  assert.match(css, /\.settings-nav-item svg\s*\{[\s\S]*flex:\s*0 0 16px !important;/)
  assert.match(css, /\.settings-nav-item span\s*\{[\s\S]*text-align:\s*left !important;/)
  assert.match(css, /\.workflow-side-file\s*\{[\s\S]*grid-template-columns:\s*32px minmax\(0, 1fr\) auto !important;/)
  assert.match(css, /\.workflow-side-file-icon\s*\{[\s\S]*background:\s*rgba\(61, 142, 134, 0\.08\) !important;/)
  assert.match(detail, /workflow-side-file-icon/)
  assert.match(detail, /workflow-side-file-path/)
  assert.match(css, /\.permission-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(4, minmax\(0, 1fr\)\);/)
})

test('templates screen matches sidebar and editor design', () => {
  assert.doesNotMatch(templatesView, /WorkflowPanel/)
  assert.match(templatesView, /templates-sidebar/)
  assert.match(templatesView, /templates-sidebar-collapsed/)
  assert.match(templatesView, /templates-sidebar-list/)
  assert.match(templatesView, /templates-sidebar-item/)
  assert.match(templatesView, /templates-editor/)
  assert.match(templatesView, /templates-editor-head/)
  // DAG canvas replaced linear editor — check canvas import instead of pipeline/step-list
  assert.match(templatesView, /WorkflowCanvas/)
  assert.match(templatesView, /templates-editor-title-row/)
  assert.match(templatesView, /templates-step-count/)
  assert.match(templatesView, /function getTemplateVisualStepCount/)
  assert.match(templatesView, /isParallelGroup/)
  assert.match(templatesView, /handleExportSelected/)
  assert.match(templatesView, />\s*复制\s*</)
  assert.match(templatesView, />\s*导出\s*</)
  assert.match(templatesView, /templateDescription=\{editDescription\}/)
  assert.match(workflowCanvas, /workflow-canvas-template-description/)
  assert.match(workflowCanvas, /onTemplateDescriptionChange\?: \(description: string\) => void/)
  assert.match(css, /\.templates-view\s*\{[\s\S]*display:\s*flex;/)
  assert.match(css, /Templates canvas EOF overrides/)
  assert.match(css, /\.templates-sidebar\s*\{[\s\S]*width:\s*260px !important;/)
  assert.match(css, /\.templates-sidebar\.templates-sidebar-collapsed\s*\{[\s\S]*width:\s*40px !important;[\s\S]*max-width:\s*40px !important;/)
  assert.match(css, /\.templates-editor-head\s*\{[\s\S]*position:\s*absolute !important;[\s\S]*top:\s*16px !important;/)
  assert.match(css, /\.workflow-canvas-shell,\s*\n\.workflow-canvas-flow,[\s\S]*radial-gradient\(var\(--neutral-canvas-dot\) 1px, transparent 1px\)/)
})

test('workflow canvas mirrors templates mock node flow, hover, and popovers', () => {
  assert.match(workflowCanvas, /const nodeTypes = \{ agent: AgentNode \}/)
  assert.match(workflowCanvas, /workflow-canvas-shell/)
  assert.match(workflowCanvas, /data-edge-count=\{edges\.length\}/)
  assert.match(workflowCanvas, /event\.clientX - stageRect\.left/)
  assert.match(workflowCanvas, /clientX: event\.clientX/)
  assert.match(workflowCanvas, /setViewport\(\{ x: 0, y: 0, zoom: 1 \}/)
  assert.match(workflowCanvas, /useState\(true\)/)
  assert.match(workflowCanvas, /panOnDrag/)
  assert.match(workflowCanvas, /workflow-canvas-agent-rail/)
  assert.match(workflowCanvas, /workflow-canvas-mini-toolbar/)
  assert.match(workflowCanvas, /workflow-canvas-context-menu/)
  assert.match(workflowCanvas, /workflow-canvas-inspector/)
  assert.match(agentNode, /workflow-agent-node/)
  assert.match(agentNode, /workflow-agent-node-vendor/)
  assert.match(agentNode, /label: 'claude'/)
  assert.doesNotMatch(agentNode, /workflow-agent-node-index/)
  assert.match(canvasSerializer, /MAX_STAGES_PER_ROW = 4/)
  assert.match(canvasSerializer, /function stagePosition/)
  assert.match(canvasSerializer, /const nodes: Node\[\] = \[\]/)
  assert.match(canvasSerializer, /let prevNodeIds: string\[\] = \[\]/)
  assert.match(canvasSerializer, /node\.type === 'agent'/)
  assert.match(canvasState, /type: 'conditional'/)
  assert.match(canvasState, /className: 'workflow-canvas-edge'/)
  assert.doesNotMatch(workflowCanvas, /BoundaryNode|CanvasEdgeOverlay|useViewport|getCanvasNodeSize|toViewportCoord/)
  assert.doesNotMatch(canvasSerializer, /canvas-start|canvas-end|type: 'boundary'|isBoundaryNode|END_X_OFFSET/)
  assert.doesNotMatch(rootBlock('.workflow-canvas-agent-rail'), /display:\s*none !important;/)
  assert.doesNotMatch(rootBlock('.workflow-canvas-mini-toolbar'), /display:\s*none !important;/)
  assert.doesNotMatch(rootBlock('.workflow-canvas-inspector-toggle'), /display:\s*none !important;/)
  assert.match(css, /\.workflow-canvas-agent-rail\s*\{[\s\S]*position:\s*relative !important;[\s\S]*margin:\s*80px 0 16px 16px !important;/)
  assert.match(css, /\.workflow-agent-node:hover\s*\{[\s\S]*transform:\s*none !important;/)
  assert.match(css, /\.workflow-node-port\s*\{[\s\S]*background:\s*var\(--neutral-border\) !important;/)
  assert.match(css, /\.workflow-node-port-out\s*\{[\s\S]*background:\s*var\(--brand-primary\) !important;/)
  assert.match(css, /\.workflow-canvas-edge-path\s*\{[\s\S]*stroke:\s*var\(--neutral-border\) !important;/)
  assert.doesNotMatch(css, /\.workflow-canvas-flow \.react-flow__edge-path\s*\{[\s\S]*opacity:\s*0 !important;/)
  assert.doesNotMatch(css, /workflow-canvas-edge-overlay|workflow-canvas-edge-overlay-path|workflow-boundary-node/)
  assert.match(css, /\.workflow-canvas-context-menu,[\s\S]*\.workflow-canvas-inspector\s*\{[\s\S]*backdrop-filter:\s*var\(--glass-blur\);/)
  assert.match(workflowCanvas, /bg:\s*'var\(--neutral-canvas\)'/)
  assert.match(workflowCanvas, /controlBackground = 'var\(--workflow-canvas-control-bg, var\(--neutral-surface-raised\)\)'/)
  assert.match(workflowCanvas, /className="workflow-canvas-property-control"/)
  assert.match(css, /\.context-menu-dropdown\s*\{[\s\S]*background:\s*var\(--glass-bg\) !important;[\s\S]*backdrop-filter:\s*var\(--glass-blur\);/)
  assert.match(css, /\.context-menu-item:hover\s*\{[\s\S]*background:\s*rgba\(61, 142, 134, 0\.06\) !important;[\s\S]*color:\s*var\(--brand-primary\) !important;/)
  assert.match(css, /\[data-theme="dark"\] \.workflow-agent-node\s*\{[\s\S]*border-color:\s*rgba\(0, 212, 170, 0\.2\) !important;/)
  assert.match(css, /\[data-theme="dark"\] \.workflow-canvas-edge-path\s*\{[\s\S]*stroke:\s*rgba\(0, 212, 170, 0\.2\) !important;/)
  assert.match(css, /\.workflow-canvas-edge-active\s*\{[\s\S]*stroke-dasharray:\s*6 4 !important;[\s\S]*animation:\s*workflow-edge-dash 1s linear infinite;/)
})

test('dark QA fixes keep workflow schedules and template agents readable', () => {
  assert.match(css, /\[data-theme="dark"\] \.schedule-history-row\s*\{[\s\S]*background:\s*rgba\(15, 25, 45, 0\.62\) !important;[\s\S]*box-shadow:\s*none !important;/)
  assert.match(css, /\[data-theme="dark"\] \.schedule-history-row span,\s*\n\[data-theme="dark"\] \.schedule-history-row small\s*\{[\s\S]*color:\s*var\(--neutral-text-secondary\) !important;/)
  assert.match(css, /\[data-theme="dark"\] \.workflow-canvas-agent-rail\s*\{[\s\S]*color:\s*var\(--neutral-text-primary\) !important;/)
  assert.match(css, /\[data-theme="dark"\] \.workflow-canvas-agent-palette-item\s*\{[\s\S]*color:\s*var\(--neutral-text-secondary\) !important;/)
  assert.match(css, /\[data-theme="dark"\] \.workflow-canvas-agent-palette-item > span\s*\{[\s\S]*color:\s*var\(--neutral-text-secondary\) !important;/)
  assert.match(css, /\[data-theme="dark"\] \.workflow-canvas-agent-palette-item button\s*\{[\s\S]*background:\s*rgba\(15, 25, 45, 0\.72\) !important;/)
  assert.match(css, /\.workflow-canvas-inspector\s*\{[\s\S]*--workflow-canvas-control-bg:\s*rgba\(255, 255, 255, 0\.72\);/)
  assert.match(css, /\[data-theme="dark"\] \.workflow-canvas-inspector\s*\{[\s\S]*--workflow-canvas-control-bg:\s*rgba\(10, 15, 26, 0\.72\);[\s\S]*--workflow-canvas-control-border:\s*rgba\(0, 212, 170, 0\.18\);/)
  assert.match(css, /\[data-theme="dark"\] \.workflow-canvas-property-control\s*\{[\s\S]*color-scheme:\s*dark !important;/)
})

test('workflow canvas agent chooser exposes agent detail panel', () => {
  assert.match(workflowCanvas, /openAgentDetail/)
  assert.match(workflowCanvas, /rightPanelMode.*'agent-detail'/)
  assert.match(workflowCanvas, /title=\{`View \$\{agent\.name\} details`\}/)
  assert.match(workflowCanvas, /<Info size=\{13\} \/>/)
  assert.match(workflowCanvas, /AgentDetailPanel/)
  assert.match(workflowCanvas, /Agent Details/)
  assert.match(workflowCanvas, /onOpenAgentDetail=\{openAgentDetail\}/)
  assert.match(workflowCanvas, /Use for \{selectedNodeData\?\.agentName/)
  assert.doesNotMatch(workflowCanvas, /AgentManager/)
})

test('templates save button uses the latest canvas steps snapshot', () => {
  assert.match(templatesView, /pendingStepsRef\.current = selectedTemplate\?\.steps \?\? null/)
  assert.match(templatesView, /void handleCanvasSave\(pendingStepsRef\.current \?\? selectedTemplate\.steps\)/)
  assert.doesNotMatch(templatesView, /if \(pendingStepsRef\.current\) \{\s*void handleCanvasSave/)
  assert.match(templatesView, /onStepsChange=\{\(steps\) => \{[\s\S]*pendingStepsRef\.current = steps/)
  assert.match(templatesView, /description: editDescription\.trim\(\) \|\| undefined/)
  assert.match(workflowCanvas, /onStepsChange\?: \(steps: import\('@shared\/types'\)\.WorkflowStepNode\[\]\) => void/)
  assert.match(workflowCanvas, /onStepsChangeRef\.current\?\.\(getSteps\(\)\)/)
})

test('template canvas selection and measurement changes do not mark templates dirty', () => {
  assert.match(canvasState, /type NodeChange/)
  assert.match(canvasState, /type EdgeChange/)
  assert.match(canvasState, /function isMutatingNodeChange\(change: NodeChange\): boolean \{[\s\S]*change\.type === 'select' \|\| change\.type === 'dimensions'[\s\S]*return false/)
  assert.match(canvasState, /if \(change\.type === 'position'\) return change\.position != null/)
  assert.match(canvasState, /function isMutatingEdgeChange\(change: EdgeChange\): boolean \{[\s\S]*return change\.type !== 'select'/)
  assert.match(canvasState, /if \(changes\.some\(isMutatingNodeChange\)\) pushHistory\(\)/)
  assert.match(canvasState, /if \(changes\.some\(isMutatingEdgeChange\)\) pushHistory\(\)/)
})

test('workflow run sort control reuses the shared Select component', () => {
  const dashboardToolbarBlock = [...css.matchAll(/\.workflow-dashboard-toolbar,\s*\n\.schedule-dashboard-toolbar\s*\{([^}]*)\}/g)].at(-1)?.[1] ?? ''

  assert.match(runsList, /import \{ Select \} from '\.\/Select'/)
  assert.match(runsList, /<div className="workflow-sort-select">[\s\S]*<Select[\s\S]*ariaLabel="运行排序"/)
  assert.match(runsList, /<Select\.Item value="newest">按时间倒序<\/Select\.Item>/)
  assert.match(runsList, /<Select\.Item value="oldest">按时间正序<\/Select\.Item>/)
  assert.match(runsList, /<Select\.Item value="name">按名称<\/Select\.Item>/)
  assert.doesNotMatch(runsList, /<select[\s\S]*workflow-sort-select/)
  assert.match(selectComponent, /ariaLabel\?: string/)
  assert.match(selectComponent, /aria-label=\{ariaLabel\}/)
  assert.match(dashboardToolbarBlock, /justify-content:\s*space-between !important;/)
  assert.match(css, /\.filter-chips\s*\{[\s\S]*flex:\s*1 1 auto !important;/)
  assert.match(css, /\.workflow-sort-select\s*\{[\s\S]*width:\s*150px !important;[\s\S]*flex:\s*0 0 150px !important;/)
  assert.match(css, /\.workflow-sort-select \.select-trigger\s*\{[\s\S]*min-height:\s*38px !important;/)
})

test('electron main window is visible for local UI review', () => {
  assert.match(mainIndex, /frame:\s*false/)
  assert.match(mainIndex, /show:\s*true/)
})

test('ui review fixture provides v4 design data without touching persisted state', () => {
  assert.match(fixture, /uiReview=v4/)
  assert.match(fixture, /Todo App · Dev Flow/)
  assert.match(fixture, /auth-refactor-pipeline/)
  assert.match(fixture, /dependency-update/)
  assert.match(fixture, /feature-branch-workflow/)
  assert.match(fixture, /docs-sync/)
  assert.match(fixture, /parallel:\s*\[/)
  assert.match(fixture, /role: 'Analyze'/)
  assert.match(fixture, /role: 'Generate Tests'/)
  assert.match(fixture, /role: 'Refactor'/)
  assert.match(fixture, /role: 'Review'/)
  assert.match(fixture, /3 running/)
  assert.match(fixture, /2 waiting/)
  assert.match(fixture, /4 模板/)
  assert.match(fixture, /\/Users\/siyuan\/work\/app-a/)
  assert.match(app, /useUiReviewFixture/)
  assert.match(app, /uiReview\.enabled \? uiReview\.agents : savedAgents/)
  assert.match(app, /uiReview\.enabled \? uiReview\.workflows : savedWorkflows/)
  assert.match(app, /uiReview\.enabled \? uiReview\.schedules : undefined/)
  assert.match(fixture, /topbarChips/)
  assert.match(fixture, /schedules: UseSchedulesResult/)
  assert.match(fixture, /createSchedules/)
  assert.match(fixture, /Nightly QA Sweep/)
  assert.match(fixture, /Dependency Audit/)
  assert.match(fixture, /scheduledBy: 'schedule-nightly-qa'/)
  assert.match(fixture, /settings:\s*\['memory references', 'local storage'\]/)
  assert.match(app, /newRunDefaults=\{uiReview\.enabled \? uiReview\.newRunDefaults : undefined\}/)
  assert.match(fixture, /status:\s*'awaiting-input'/)
  assert.match(fixture, /stepStatuses:\s*\['done', 'awaiting-input'\]/)
})

test('ui review workflow detail suppresses production-only controls for screenshot parity', () => {
  assert.match(app, /app-ui-review/)
  assert.match(detail, /workflow-confirm-step/)
  assert.match(detail, /run\.status === 'running' \|\| run\.status === 'awaiting-confirm'/)
  assert.match(detail, /workflow-run-warning/)
  assert.match(detail, /codex-layout/)
  assert.match(css, /\.app-ui-review \.workflow-confirm-step\s*\{[\s\S]*display:\s*none;/)
  assert.match(fixture, /gitSafetyMessage/)
  assert.match(fixture, /displayPath/)
  assert.match(fixture, /listMeta/)
  assert.match(fixture, /tailLines/)
  assert.match(fixture, /CRUD done/)
  assert.match(fixture, /devFlowStepDisplayNames/)
  assert.match(fixture, /'修复反馈'[\s\S]*'最终验收'[\s\S]*'总结沉淀'[\s\S]*'收尾检查'/)
  assert.match(fixture, /需求', '设计', '开发', '测试'/)
  assert.match(runsList, /listMeta/)
  assert.match(detail, /displayPath/)
  assert.match(detail, /className="danger"/)
  assert.match(runsList, /workflow-run-card-status/)
  assert.match(drawer, /formatTemplateOption/)
  assert.match(drawer, /previewSteps/)
  assert.match(drawer, /selectedTemplate\?\.steps\.length/)
  assert.match(drawer, /aria-label="Close"/)
  assert.match(css, /\.workflow-run-card-status-awaiting-confirm/)
  assert.match(css, /\.workflow-new-run-body textarea\s*\{[\s\S]*min-height:\s*82px !important;[\s\S]*max-height:\s*120px !important;/)
  assert.doesNotMatch(fixture, /kind: 'system', text: 'handoff ready · waiting for confirm'/)
  assert.match(app, /app-ui-review/)
})

test('ui review chrome matches v4 mockup navigation and composer', () => {
  assert.match(mockNav, /type UiReviewMockNavActive = 'workflow' \| 'new-run' \| 'schedules' \| 'templates' \| 'agents' \| 'single' \| 'settings'/)
  assert.match(mockNav, /New Run Drawer/)
  assert.match(mockNav, /Workflow/)
  assert.match(mockNav, /Schedules/)
  assert.match(mockNav, /Templates/)
  assert.match(mockNav, /Agents/)
  assert.match(mockNav, /Single/)
  assert.match(mockNav, /Settings/)
  assert.match(css, /\.ui-review-mock-nav\s*\{[\s\S]*position:\s*fixed;[\s\S]*bottom:\s*12px;/)
  assert.match(css, /\.ui-review-mock-nav-item-active\s*\{/)
  assert.match(app, /UiReviewMockNav/)
  assert.match(modeRail, /railIcon/)
  assert.match(modeRail, /LayoutGrid[\s\S]*CalendarClock[\s\S]*Layers[\s\S]*Bot[\s\S]*MessageCircle[\s\S]*Settings/)
  assert.match(app, /type UiReviewWorkflowSurface = 'workflow' \| 'new-run'/)
  assert.match(app, /useState<UiReviewWorkflowSurface>\('workflow'\)/)
  assert.match(app, /uiReview\.enabled && uiReviewWorkflowSurface === 'new-run'[\s\S]*\? '工作流 · 新建运行'[\s\S]*: '工作流'/)
  assert.match(workspace, /uiReviewEnabled/)
  assert.match(workspace, /onUiReviewSurfaceChange\?: \(surface: 'workflow' \| 'new-run'\) => void/)
  assert.match(workspace, /onUiReviewSurfaceChange\?\.\(newRunDrawerOpen \? 'new-run' : 'workflow'\)/)
  assert.match(workspace, /UiReviewMockNav/)
  assert.match(workspace, /uiReviewEnabled=\{uiReviewEnabled\}/)
  assert.match(app, /newRunDefaults=\{uiReview\.enabled \? uiReview\.newRunDefaults : undefined\}/)
  assert.match(app, /onUiReviewSurfaceChange=\{setUiReviewWorkflowSurface\}/)
  assert.match(workspace, /<NewWorkflowRunDrawer[\s\S]*uiReviewEnabled=\{uiReviewEnabled\}/)
  assert.match(workspace, /newRunDrawerOpen \? 'new-run' : 'workflow'/)
  assert.match(workspace, /向当前 workflow \/ step 发送消息\.\.\./)
  assert.match(detail, /uiReviewEnabled\?: boolean/)
  assert.match(detail, />\s*重新运行步骤\s*</)
  assert.match(detail, /<textarea[\s\S]*placeholder=\{composerPlaceholder\}/)
  // The composer uses <textarea> (Enter sends, Shift+Enter inserts a newline), not <input>
  assert.ok(!/<input[^>]*placeholder=\{composerPlaceholder\}/.test(detail))
  assert.match(detail, /workflow-cli-composer/)
  assert.match(drawer, /uiReviewEnabled\?: boolean/)
  assert.match(drawer, /if \(!uiReviewEnabled\) rememberProjectPath\(projectPath\.trim\(\)\)/)
  assert.match(drawer, /\{!uiReviewEnabled && \([\s\S]*<button type="button" onClick=\{pickDir\} aria-label="Browse project directory"/)
  assert.match(drawer, />\s*启动运行\s*</)
  assert.match(drawer, /uiReviewEnabled \? selectedTemplate\?\.name/)
  assert.doesNotMatch(css, /\.app-ui-review button\s*\{/)
  assert.match(css, /\.workflow-new-run-body input,\s*\n\.workflow-new-run-body textarea,\s*\n\.workflow-new-run-body \.select-trigger\s*\{[\s\S]*min-height:\s*34px !important;[\s\S]*font-size:\s*12px !important;[\s\S]*padding:\s*7px 11px !important;/)
  assert.match(css, /\.workflow-runs-actions button,\s*\n\.workflow-run-detail-actions button,\s*\n\.workflow-cli-composer button,\s*\n\.workflow-new-run-header button,\s*\n\.workflow-new-run-actions button,\s*\n\.agent-list-header button,\s*\n\.agent-editor-actions button\s*\{[\s\S]*font-weight:\s*750;/)
  assert.match(css, /\.workflow-cli-composer\s*\{[\s\S]*display:\s*flex;[\s\S]*flex-direction:\s*column;[\s\S]*padding:\s*10px 12px;/)
  assert.match(css, /\.workflow-cli-composer[\s\S]*\.composer-row\s*\{[\s\S]*display:\s*grid;[\s\S]*grid-template-columns:\s*34px minmax\(0,\s*1fr\) 34px;[\s\S]*align-items:\s*center;/)
  assert.match(css, /\.workflow-cli-composer \.composer-input\s*\{[\s\S]*min-width:\s*0;[\s\S]*min-height:\s*34px;/)
  assert.match(css, /\.workflow-run-card\s*\{[\s\S]*justify-content:\s*stretch;[\s\S]*justify-items:\s*stretch;/)
  assert.match(css, /\.workflow-step-nav-card\s*\{[\s\S]*justify-content:\s*stretch;[\s\S]*justify-items:\s*stretch;/)
  assert.match(css, /\.workflow-steps-title strong,\s*\n\.workflow-template-preview \.field-row-between > span\s*\{[\s\S]*border:\s*1px solid var\(--border\);[\s\S]*border-radius:\s*999px;[\s\S]*padding:\s*4px 9px;/)
  assert.match(css, /\.workflow-template-preview strong\s*\{[\s\S]*font-size:\s*15px;/)
  assert.match(css, /\.app-ui-review \.workflow-cli-composer button:disabled\s*\{[\s\S]*background:\s*var\(--accent\);/)
})
